# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SPLeakDetector' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'FBRetainCycleDetector', '~> 0.1.4'
  # Pods for SPLeakDetector

end
